include:
  # General
  - project: softwareradiosystems/testing-tools
    ref: "44"
    file: .gitlab/ci-shared/setup/all.yml
  - project: softwareradiosystems/testing-tools
    ref: "44"
    file: .gitlab/ci-shared/features/autorebaser.yml
  - project: softwareradiosystems/testing-tools
    ref: "44"
    file: .gitlab/ci-shared/features/ci_checks.yml
  - project: softwareradiosystems/testing-tools
    ref: "44"
    file: .gitlab/ci-shared/features/jobs_cleaner.yml
  - project: softwareradiosystems/testing-tools
    ref: "44"
    file: .gitlab/ci-shared/features/notify_status.yml
  - project: softwareradiosystems/testing-tools
    ref: "44"
    file: .gitlab/ci-shared/features/pr_reminder.yml
  - project: softwareradiosystems/testing-tools
    ref: "44"
    file: .gitlab/ci-shared/features/project_configurator.yml
  - project: softwareradiosystems/testing-tools
    ref: "44"
    file: .gitlab/ci-shared/features/repo_sanity.yml
  - project: softwareradiosystems/testing-tools
    ref: "44"
    file: .gitlab/ci-shared/features/scheduler.yml

stages:
  - ci
  - build
  - publish doc

################################################################################
# Doc generation
################################################################################
generate-pages:
  stage: build
  rules:
    - if: $ON_SCHEDULE
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_MR
  image: $CR_REGISTRY_URI/testing-tools/doxygen:1.5.0
  script:
    # Clone
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/softwareradiosystems/srsgnb.git

    - export pwd="$( pwd )"
    - cd srsgnb
    - mkdir build
    - cd build
    - cmake -G Ninja ..
    - ninja doxygen

    - mkdir -p $pwd/docs/source/.doxygen/xml
    - cd docs
    - mv xml/* $pwd/docs/source/.doxygen/xml

    # Install requirements
    - cd $pwd
    - pip install -r requirements.txt
    - cd docs

    # Make html and move to public
    - make html
    - mv build/html ../public
  artifacts:
    paths:
      - public

################################################################################
# Publish doc
################################################################################
pages:
  stage: publish doc
  rules:
    - if: $ON_SCHEDULE
    - if: $ON_DEFAULT_BRANCH
  needs:
    - job: generate-pages
  script:
    - echo "Publishing..."
  artifacts:
    paths:
      - public
